### ISSUE TITLE
how to run this project step by step plz..?

### ISSUE THREAD

**Issue by remazevs** [mysteryjeans/doorsale#4]
give me plz steps...i made doorsale_site and run ...but than i dont noe what i have to do next..plz help..?

**Comment by mysteryjeans** [comment]
Doorsale coded on the philosophy of django, you can customise templates by overriding the templates & css like you customise for django admin.

**Comment by remazevs** [comment]
thanks for your replay.Actually I want to run your project in my pc.I have basic knowledge of python and django.i want  source code for practice.
