### ISSUE TITLE
cart_id Issue while final order stage process

### ISSUE THREAD

**Issue by shazianusrat** [mysteryjeans/doorsale#8]
Hello Faraz,

I am having an issue while checking out and clicking on "order" button. Can you kindly help to fix it. Also a little two liner brief would be appreciated that why didn't you created a model field for cart_id instead of declaring it as variable?
Error says that in sales/views line 351 it cannot extract a key something given below:
**KeyError at /sales/checkout/order**
Another issue is that when I upload images for a product it pops up error:
**"no such table: thumbnail_kvstore"**
Reason is that the package doesn't include any migrations with it and I don't know how to create one because with migrate its not working. Will be thankful for your kind advise.
Overall this is best ecommerce recipe for newbie like me and I really am looking forward for your kind answer to take a moment off from you to help me get over these small problems.
Thank you.
Regards,
Shazia

**Comment by MUDASSARHASHMI** [comment]
Shazia,
You need to copy migrations folder in your sorl/thumbnail github as by default with pip or pypy package it is not copying migrations. After that if the problem persists then make sure that your email is communicating to your smtp server via Django application or doorsale repo in your case. If both things fixed you won't have any errors. 
On windows in lib/site-packages/sorl/thumbnail/Create"migrations"FolderHere/With two files here(__init__.py, 0001_initial.py.

On non windows OS in lib/site-packages/python3.5/sorl/thumbnail/migrations/with two files as above

I happen to install it on my ubuntu and windows both but I couldn't got any error. So I followed your errors above and recreated the issues same like you are getting. 
Let me know if issue still persists. 

Regards,
Mudassar

**Comment by shazianusrat** [comment]
I am surprised to see that it works with only putting in email. That shows that error was misleading. Thank you for your help Mudassar it really worked for me. But still can you give me a clue why would it pop up such error for email settings?

Thanks for help and its working for me now.
So I am closing the issue.
